version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:8080" # Map port 8080 on the host to port 8080 on the frontend container
    volumes:
      - ./frontend:/app/frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8081:80" # Map port 8081 on the host to port 80 on the backend container
    volumes:
      - ./backend:/var/www/html

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"