# Use a base image with Node.js pre-installed
FROM node:latest AS builder

# install simple http server for serving static content
# RUN npm install -g http-server

# Set the working directory in the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the container (if available)
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY frontend/ ./

# Build the Vue.js application
RUN npm run build

# Expose port 80 to the Docker host, so external connections can access the container
EXPOSE 8070

# Command to run the Vue.js application
CMD ["npm", "run", "dev"]
